### ISSUE TITLE
slight login change

### ISSUE THREAD

**Issue by thelonehamster** [baxter-cs/AndOre#175]
when typing in a password to login, the password is displayed as text. A nice fix would be to have it be this

`<input placeholder="Ore" id="login_password" type="password" class="validate">`

instead of this

`<input placeholder="Ore" id="login_password" type="text" class="validate">`
i do not know how to change that though.

**Comment by JCharante** [comment]
Fixed in https://github.com/baxter-cs/AndOre/commit/dee1094022a0d1abbfae6f2707ef9721c37afe13
